### ISSUE TITLE
Error: header too long

### ISSUE THREAD

**Issue by ROG3R-DEV** [Bezouro/nubank.js#3]
Olá, fiz o setup seguindo os passos na documentação e gerei o certificado. Porém estou tendo o erro abaixo que parece estar retornando da api.

```shell
Error: header too long
    at configSecureContext (node:internal/tls/secure-context:278:15)
    at Object.createSecureContext (node:_tls_common:117:3)
    at Object.connect (node:_tls_wrap:1621:48)
    at Agent.createConnection (node:https:143:22)
    at Agent.createSocket (node:_http_agent:341:26)
    at Agent.addRequest (node:_http_agent:292:10)
    at new ClientRequest (node:_http_client:305:16)
    at Object.request (node:https:353:10)
    at RedirectableRequest._performRequest (/Users/rog3r/Downloads/nubank-api/node_modules/follow-redirects/index.js:284:24)
    at new RedirectableRequest (/Users/rog3r/Downloads/nubank-api/node_modules/follow-redirects/index.js:66:8)
[nodemon] app crashed - waiting for file changes before starting...
``` 

Alguma ideia do que pode ser?

Obrigado!

**Comment by Bezouro** [comment]
Aopa, vou dar uma verificada hoje e já trago novidades ✌🏼

**Comment by Bezouro** [comment]
Não consegui reproduzir aqui, eu lancei uma versão nova, será que ainda persiste?
