### ISSUE TITLE
Recebendo o erro "TypeError: tmp.length is not a function" quando gerando o certificado através da CLI

### ISSUE THREAD

**Issue by joaoscheuermann** [Bezouro/nubank.js#4]
Estou recebendo o seguinte erro quando tento gerar o certificado através da CLI:
```
Requesting code...
TypeError: tmp.length is not a function
    at forge.aes.Algorithm.initialize (C:\Users\jao\Documents\git\personal\automation\node_modules\node-forge\lib\aes.js:203:19)
    at new forge.cipher.BlockCipher (C:\Users\jao\Documents\git\personal\automation\node_modules\node-forge\lib\cipher.js:118:18)
    at Object.forge.cipher.createCipher (C:\Users\jao\Documents\git\personal\automation\node_modules\node-forge\lib\cipher.js:42:10)
    at Function.CertificateGenerator.encryptString (C:\Users\jao\Documents\git\personal\automation\node_modules\nubank.ts\dist\utils\certificateGenerator.js:122:53)
    at CertificateGenerator.saveState (C:\Users\jao\Documents\git\personal\automation\node_modules\nubank.ts\dist\utils\certificateGenerator.js:119:75)
    at CertificateGenerator.<anonymous> (C:\Users\jao\Documents\git\personal\automation\node_modules\nubank.ts\dist\utils\certificateGenerator.js:162:30)
    at step (C:\Users\jao\Documents\git\personal\automation\node_modules\nubank.ts\dist\utils\certificateGenerator.js:56:23)
    at Object.throw (C:\Users\jao\Documents\git\personal\automation\node_modules\nubank.ts\dist\utils\certificateGenerator.js:37:53)
    at rejected (C:\Users\jao\Documents\git\personal\automation\node_modules\nubank.ts\dist\utils\certificateGenerator.js:29:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Bezouro** [comment]
Qual o seu sistema operacional?

**Comment by joaoscheuermann** [comment]
Windows 10
